---
- name: Configure hosts & deploy application
  hosts: app
  become: true
  vars:
   db_host: 10.132.0.54
  
  tasks:
    - name: Add unit file for Puma
      copy: src=files/puma.service dest=/etc/systemd/system/puma.service
      notify: reload puma

    - name: Instance facts
      gcp_compute_instance_facts:
        project: infra-235119
        zone: europe-west1-b
        filters: name=reddit-db
        auth_kind: serviceaccount
        service_account_file: /Users/akozhin/infra-235119-3cab3055011e.json
      register: instance

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/appuser/db_config
        owner: appuser
        group: appuser

    - name: enable puma
      systemd: name=puma enabled=yes

  handlers:
  - name: reload puma
    systemd: name=puma state=restarted
